// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/v2beta1/context.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DFContext;
@class GPBFieldMask;
@class GPBStruct;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DFContextRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DFContextRoot : GPBRootObject
@end

#pragma mark - DFContext

typedef GPB_ENUM(DFContext_FieldNumber) {
  DFContext_FieldNumber_Name = 1,
  DFContext_FieldNumber_LifespanCount = 2,
  DFContext_FieldNumber_Parameters = 3,
};

/**
 * Represents a context.
 **/
@interface DFContext : GPBMessage

/**
 * Required. The unique identifier of the context. Format:
 * `projects/<Project ID>/agent/sessions/<Session ID>/contexts/<Context ID>`,
 * or `projects/<Project ID>/agent/environments/<Environment ID>/users/<User
 * ID>/sessions/<Session ID>/contexts/<Context ID>`. The `Context ID` is
 * always converted to lowercase. If `Environment ID` is not specified, we
 * assume default 'draft' environment. If `User ID` is not specified, we
 * assume default '-' user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Optional. The number of conversational query requests after which the
 * context expires. If set to `0` (the default) the context expires
 * immediately. Contexts expire automatically after 10 minutes even if there
 * are no matching queries.
 **/
@property(nonatomic, readwrite) int32_t lifespanCount;

/**
 * Optional. The collection of parameters associated with this context.
 * Refer to [this doc](https://dialogflow.com/docs/actions-and-parameters) for
 * syntax.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *parameters;
/** Test to see if @c parameters has been set. */
@property(nonatomic, readwrite) BOOL hasParameters;

@end

#pragma mark - DFListContextsRequest

typedef GPB_ENUM(DFListContextsRequest_FieldNumber) {
  DFListContextsRequest_FieldNumber_Parent = 1,
  DFListContextsRequest_FieldNumber_PageSize = 2,
  DFListContextsRequest_FieldNumber_PageToken = 3,
};

/**
 * The request message for [Contexts.ListContexts][google.cloud.dialogflow.v2beta1.Contexts.ListContexts].
 **/
@interface DFListContextsRequest : GPBMessage

/**
 * Required. The session to list all contexts from.
 * Format: `projects/<Project ID>/agent/sessions/<Session ID>` or
 * `projects/<Project ID>/agent/environments/<Environment ID>/users/<User
 * ID>/sessions/<Session ID>`. If `Environment ID` is not specified, we assume
 * default 'draft' environment. If `User ID` is not specified, we assume
 * default '-' user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *parent;

/**
 * Optional. The maximum number of items to return in a single page. By
 * default 100 and at most 1000.
 **/
@property(nonatomic, readwrite) int32_t pageSize;

/** Optional. The next_page_token value returned from a previous list request. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@end

#pragma mark - DFListContextsResponse

typedef GPB_ENUM(DFListContextsResponse_FieldNumber) {
  DFListContextsResponse_FieldNumber_ContextsArray = 1,
  DFListContextsResponse_FieldNumber_NextPageToken = 2,
};

/**
 * The response message for [Contexts.ListContexts][google.cloud.dialogflow.v2beta1.Contexts.ListContexts].
 **/
@interface DFListContextsResponse : GPBMessage

/**
 * The list of contexts. There will be a maximum number of items
 * returned based on the page_size field in the request.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DFContext*> *contextsArray;
/** The number of items in @c contextsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contextsArray_Count;

/**
 * Token to retrieve the next page of results, or empty if there are no
 * more results in the list.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - DFGetContextRequest

typedef GPB_ENUM(DFGetContextRequest_FieldNumber) {
  DFGetContextRequest_FieldNumber_Name = 1,
};

/**
 * The request message for [Contexts.GetContext][google.cloud.dialogflow.v2beta1.Contexts.GetContext].
 **/
@interface DFGetContextRequest : GPBMessage

/**
 * Required. The name of the context. Format:
 * `projects/<Project ID>/agent/sessions/<Session ID>/contexts/<Context ID>`
 * or `projects/<Project ID>/agent/environments/<Environment ID>/users/<User
 * ID>/sessions/<Session ID>/contexts/<Context ID>`. If `Environment ID` is
 * not specified, we assume default 'draft' environment. If `User ID` is not
 * specified, we assume default '-' user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - DFCreateContextRequest

typedef GPB_ENUM(DFCreateContextRequest_FieldNumber) {
  DFCreateContextRequest_FieldNumber_Parent = 1,
  DFCreateContextRequest_FieldNumber_Context = 2,
};

/**
 * The request message for [Contexts.CreateContext][google.cloud.dialogflow.v2beta1.Contexts.CreateContext].
 **/
@interface DFCreateContextRequest : GPBMessage

/**
 * Required. The session to create a context for.
 * Format: `projects/<Project ID>/agent/sessions/<Session ID>` or
 * `projects/<Project ID>/agent/environments/<Environment ID>/users/<User
 * ID>/sessions/<Session ID>`. If `Environment ID` is not specified, we assume
 * default 'draft' environment. If `User ID` is not specified, we assume
 * default '-' user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *parent;

/** Required. The context to create. */
@property(nonatomic, readwrite, strong, null_resettable) DFContext *context;
/** Test to see if @c context has been set. */
@property(nonatomic, readwrite) BOOL hasContext;

@end

#pragma mark - DFUpdateContextRequest

typedef GPB_ENUM(DFUpdateContextRequest_FieldNumber) {
  DFUpdateContextRequest_FieldNumber_Context = 1,
  DFUpdateContextRequest_FieldNumber_UpdateMask = 2,
};

/**
 * The request message for [Contexts.UpdateContext][google.cloud.dialogflow.v2beta1.Contexts.UpdateContext].
 **/
@interface DFUpdateContextRequest : GPBMessage

/** Required. The context to update. */
@property(nonatomic, readwrite, strong, null_resettable) DFContext *context;
/** Test to see if @c context has been set. */
@property(nonatomic, readwrite) BOOL hasContext;

/** Optional. The mask to control which fields get updated. */
@property(nonatomic, readwrite, strong, null_resettable) GPBFieldMask *updateMask;
/** Test to see if @c updateMask has been set. */
@property(nonatomic, readwrite) BOOL hasUpdateMask;

@end

#pragma mark - DFDeleteContextRequest

typedef GPB_ENUM(DFDeleteContextRequest_FieldNumber) {
  DFDeleteContextRequest_FieldNumber_Name = 1,
};

/**
 * The request message for [Contexts.DeleteContext][google.cloud.dialogflow.v2beta1.Contexts.DeleteContext].
 **/
@interface DFDeleteContextRequest : GPBMessage

/**
 * Required. The name of the context to delete. Format:
 * `projects/<Project ID>/agent/sessions/<Session ID>/contexts/<Context ID>`
 * or `projects/<Project ID>/agent/environments/<Environment ID>/users/<User
 * ID>/sessions/<Session ID>/contexts/<Context ID>`. If `Environment ID` is
 * not specified, we assume default 'draft' environment. If `User ID` is not
 * specified, we assume default '-' user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - DFDeleteAllContextsRequest

typedef GPB_ENUM(DFDeleteAllContextsRequest_FieldNumber) {
  DFDeleteAllContextsRequest_FieldNumber_Parent = 1,
};

/**
 * The request message for [Contexts.DeleteAllContexts][google.cloud.dialogflow.v2beta1.Contexts.DeleteAllContexts].
 **/
@interface DFDeleteAllContextsRequest : GPBMessage

/**
 * Required. The name of the session to delete all contexts from. Format:
 * `projects/<Project ID>/agent/sessions/<Session ID>` or `projects/<Project
 * ID>/agent/environments/<Environment ID>/users/<User ID>/sessions/<Session
 * ID>`. If `Environment ID` is not specified we assume default 'draft'
 * environment. If `User ID` is not specified, we assume default '-' user.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *parent;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
