// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/v2beta1/knowledge_base.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DFKnowledgeBase;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DFKnowledgeBaseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DFKnowledgeBaseRoot : GPBRootObject
@end

#pragma mark - DFKnowledgeBase

typedef GPB_ENUM(DFKnowledgeBase_FieldNumber) {
  DFKnowledgeBase_FieldNumber_Name = 1,
  DFKnowledgeBase_FieldNumber_DisplayName = 2,
};

/**
 * Represents knowledge base resource.
 **/
@interface DFKnowledgeBase : GPBMessage

/**
 * The knowledge base resource name.
 * The name must be empty when creating a knowledge base.
 * Format: `projects/<Project ID>/knowledgeBases/<Knowledge Base ID>`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Required. The display name of the knowledge base. The name must be 1024
 * bytes or less; otherwise, the creation request fails.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *displayName;

@end

#pragma mark - DFListKnowledgeBasesRequest

typedef GPB_ENUM(DFListKnowledgeBasesRequest_FieldNumber) {
  DFListKnowledgeBasesRequest_FieldNumber_Parent = 1,
  DFListKnowledgeBasesRequest_FieldNumber_PageSize = 2,
  DFListKnowledgeBasesRequest_FieldNumber_PageToken = 3,
};

/**
 * Request message for [KnowledgeBases.ListKnowledgeBases][google.cloud.dialogflow.v2beta1.KnowledgeBases.ListKnowledgeBases].
 **/
@interface DFListKnowledgeBasesRequest : GPBMessage

/**
 * Required. The agent to list of knowledge bases for.
 * Format: `projects/<Project ID>/agent`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *parent;

/**
 * Optional. The maximum number of items to return in a single page. By
 * default 10 and at most 100.
 **/
@property(nonatomic, readwrite) int32_t pageSize;

/** Optional. The next_page_token value returned from a previous list request. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@end

#pragma mark - DFListKnowledgeBasesResponse

typedef GPB_ENUM(DFListKnowledgeBasesResponse_FieldNumber) {
  DFListKnowledgeBasesResponse_FieldNumber_KnowledgeBasesArray = 1,
  DFListKnowledgeBasesResponse_FieldNumber_NextPageToken = 2,
};

/**
 * Response message for [KnowledgeBases.ListKnowledgeBases][google.cloud.dialogflow.v2beta1.KnowledgeBases.ListKnowledgeBases].
 **/
@interface DFListKnowledgeBasesResponse : GPBMessage

/** The list of knowledge bases. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DFKnowledgeBase*> *knowledgeBasesArray;
/** The number of items in @c knowledgeBasesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger knowledgeBasesArray_Count;

/**
 * Token to retrieve the next page of results, or empty if there are no
 * more results in the list.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - DFGetKnowledgeBaseRequest

typedef GPB_ENUM(DFGetKnowledgeBaseRequest_FieldNumber) {
  DFGetKnowledgeBaseRequest_FieldNumber_Name = 1,
};

/**
 * Request message for [KnowledgeBase.GetDocument][].
 **/
@interface DFGetKnowledgeBaseRequest : GPBMessage

/**
 * Required. The name of the knowledge base to retrieve.
 * Format `projects/<Project ID>/knowledgeBases/<Knowledge Base ID>`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - DFCreateKnowledgeBaseRequest

typedef GPB_ENUM(DFCreateKnowledgeBaseRequest_FieldNumber) {
  DFCreateKnowledgeBaseRequest_FieldNumber_Parent = 1,
  DFCreateKnowledgeBaseRequest_FieldNumber_KnowledgeBase = 2,
};

/**
 * Request message for [KnowledgeBases.CreateKnowledgeBase][google.cloud.dialogflow.v2beta1.KnowledgeBases.CreateKnowledgeBase].
 **/
@interface DFCreateKnowledgeBaseRequest : GPBMessage

/**
 * Required. The agent to create a knowledge base for.
 * Format: `projects/<Project ID>/agent`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *parent;

/** Required. The knowledge base to create. */
@property(nonatomic, readwrite, strong, null_resettable) DFKnowledgeBase *knowledgeBase;
/** Test to see if @c knowledgeBase has been set. */
@property(nonatomic, readwrite) BOOL hasKnowledgeBase;

@end

#pragma mark - DFDeleteKnowledgeBaseRequest

typedef GPB_ENUM(DFDeleteKnowledgeBaseRequest_FieldNumber) {
  DFDeleteKnowledgeBaseRequest_FieldNumber_Name = 1,
  DFDeleteKnowledgeBaseRequest_FieldNumber_Force = 2,
};

/**
 * Request message for [KnowledgeBases.DeleteKnowledgeBase][google.cloud.dialogflow.v2beta1.KnowledgeBases.DeleteKnowledgeBase].
 **/
@interface DFDeleteKnowledgeBaseRequest : GPBMessage

/**
 * Required. The name of the knowledge base to delete.
 * Format: `projects/<Project ID>/knowledgeBases/<Knowledge Base ID>`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Optional. Force deletes the knowledge base. When set to true, any documents
 * in the knowledge base are also deleted.
 **/
@property(nonatomic, readwrite) BOOL force;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
