// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/v2beta1/tier.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AgentTier;
@class GPBFieldMask;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Tier

/** Represents the agent tier. */
typedef GPB_ENUM(Tier) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Tier_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Not specified. This value should never be used. */
  Tier_TierUnspecified = 0,

  /** Standard tier. */
  Tier_TierStandard = 1,

  /** Enterprise tier. */
  Tier_TierEnterprise = 2,
};

GPBEnumDescriptor *Tier_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Tier_IsValidValue(int32_t value);

#pragma mark - TierRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TierRoot : GPBRootObject
@end

#pragma mark - AgentTier

typedef GPB_ENUM(AgentTier_FieldNumber) {
  AgentTier_FieldNumber_Tier = 1,
};

/**
 * Represents the agent tier.
 **/
@interface AgentTier : GPBMessage

/** Required. The agent tier. */
@property(nonatomic, readwrite) Tier tier;

@end

/**
 * Fetches the raw value of a @c AgentTier's @c tier property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AgentTier_Tier_RawValue(AgentTier *message);
/**
 * Sets the raw value of an @c AgentTier's @c tier property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAgentTier_Tier_RawValue(AgentTier *message, int32_t value);

#pragma mark - GetAgentTierRequest

typedef GPB_ENUM(GetAgentTierRequest_FieldNumber) {
  GetAgentTierRequest_FieldNumber_Name = 1,
};

/**
 * The request message for [Tiers.GetAgentTier].
 **/
@interface GetAgentTierRequest : GPBMessage

/**
 * Required. The project to retrieve the tier of.
 * Format: `projects/<Project ID>`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - UpdateAgentTierRequest

typedef GPB_ENUM(UpdateAgentTierRequest_FieldNumber) {
  UpdateAgentTierRequest_FieldNumber_Name = 1,
  UpdateAgentTierRequest_FieldNumber_AgentTier = 2,
  UpdateAgentTierRequest_FieldNumber_UpdateMask = 3,
};

/**
 * The request message for [Tiers.UpdateAgentTier].
 **/
@interface UpdateAgentTierRequest : GPBMessage

/**
 * Required. The project to update the tier of.
 * Format: `projects/<Project ID>`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Required. The agent tier. */
@property(nonatomic, readwrite, strong, null_resettable) AgentTier *agentTier;
/** Test to see if @c agentTier has been set. */
@property(nonatomic, readwrite) BOOL hasAgentTier;

/** Optional. The mask to control which fields get updated. */
@property(nonatomic, readwrite, strong, null_resettable) GPBFieldMask *updateMask;
/** Test to see if @c updateMask has been set. */
@property(nonatomic, readwrite) BOOL hasUpdateMask;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
