// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/v2beta1/webhook.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DFContext;
@class DFEventInput;
@class DFIntent_Message;
@class DFOriginalDetectIntentRequest;
@class DFQueryResult;
@class GPBStruct;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DFWebhookRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DFWebhookRoot : GPBRootObject
@end

#pragma mark - DFWebhookRequest

typedef GPB_ENUM(DFWebhookRequest_FieldNumber) {
  DFWebhookRequest_FieldNumber_ResponseId = 1,
  DFWebhookRequest_FieldNumber_QueryResult = 2,
  DFWebhookRequest_FieldNumber_OriginalDetectIntentRequest = 3,
  DFWebhookRequest_FieldNumber_Session = 4,
  DFWebhookRequest_FieldNumber_AlternativeQueryResultsArray = 5,
};

/**
 * The request message for a webhook call.
 **/
@interface DFWebhookRequest : GPBMessage

/**
 * The unique identifier of detectIntent request session.
 * Can be used to identify end-user inside webhook implementation.
 * Format: `projects/<Project ID>/agent/sessions/<Session ID>`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *session;

/**
 * The unique identifier of the response. Contains the same value as
 * `[Streaming]DetectIntentResponse.response_id`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *responseId;

/**
 * The result of the conversational query or event processing. Contains the
 * same value as `[Streaming]DetectIntentResponse.query_result`.
 **/
@property(nonatomic, readwrite, strong, null_resettable) DFQueryResult *queryResult;
/** Test to see if @c queryResult has been set. */
@property(nonatomic, readwrite) BOOL hasQueryResult;

/** Alternative query results from KnowledgeService. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DFQueryResult*> *alternativeQueryResultsArray;
/** The number of items in @c alternativeQueryResultsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger alternativeQueryResultsArray_Count;

/**
 * Optional. The contents of the original request that was passed to
 * `[Streaming]DetectIntent` call.
 **/
@property(nonatomic, readwrite, strong, null_resettable) DFOriginalDetectIntentRequest *originalDetectIntentRequest;
/** Test to see if @c originalDetectIntentRequest has been set. */
@property(nonatomic, readwrite) BOOL hasOriginalDetectIntentRequest;

@end

#pragma mark - DFWebhookResponse

typedef GPB_ENUM(DFWebhookResponse_FieldNumber) {
  DFWebhookResponse_FieldNumber_FulfillmentText = 1,
  DFWebhookResponse_FieldNumber_FulfillmentMessagesArray = 2,
  DFWebhookResponse_FieldNumber_Source = 3,
  DFWebhookResponse_FieldNumber_Payload = 4,
  DFWebhookResponse_FieldNumber_OutputContextsArray = 5,
  DFWebhookResponse_FieldNumber_FollowupEventInput = 6,
  DFWebhookResponse_FieldNumber_EndInteraction = 8,
};

/**
 * The response message for a webhook call.
 **/
@interface DFWebhookResponse : GPBMessage

/**
 * Optional. The text to be shown on the screen. This value is passed directly
 * to `QueryResult.fulfillment_text`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *fulfillmentText;

/**
 * Optional. The collection of rich messages to present to the user. This
 * value is passed directly to `QueryResult.fulfillment_messages`.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DFIntent_Message*> *fulfillmentMessagesArray;
/** The number of items in @c fulfillmentMessagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fulfillmentMessagesArray_Count;

/** Optional. This value is passed directly to `QueryResult.webhook_source`. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *source;

/**
 * Optional. This value is passed directly to `QueryResult.webhook_payload`.
 * See the related `fulfillment_messages[i].payload field`, which may be used
 * as an alternative to this field.
 *
 * This field can be used for Actions on Google responses.
 * It should have a structure similar to the JSON message shown here. For more
 * information, see
 * [Actions on Google Webhook
 * Format](https://developers.google.com/actions/dialogflow/webhook)
 * <pre>{
 *   "google": {
 *     "expectUserResponse": true,
 *     "richResponse": {
 *       "items": [
 *         {
 *           "simpleResponse": {
 *             "textToSpeech": "this is a simple response"
 *           }
 *         }
 *       ]
 *     }
 *   }
 * }</pre>
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *payload;
/** Test to see if @c payload has been set. */
@property(nonatomic, readwrite) BOOL hasPayload;

/**
 * Optional. The collection of output contexts. This value is passed directly
 * to `QueryResult.output_contexts`.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DFContext*> *outputContextsArray;
/** The number of items in @c outputContextsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger outputContextsArray_Count;

/**
 * Optional. Makes the platform immediately invoke another `DetectIntent` call
 * internally with the specified event as input.
 **/
@property(nonatomic, readwrite, strong, null_resettable) DFEventInput *followupEventInput;
/** Test to see if @c followupEventInput has been set. */
@property(nonatomic, readwrite) BOOL hasFollowupEventInput;

/**
 * Optional. Indicates that this intent ends an interaction. Some integrations
 * (e.g., Actions on Google or Dialogflow phone gateway) use this information
 * to close interaction with an end user. Default is false.
 **/
@property(nonatomic, readwrite) BOOL endInteraction;

@end

#pragma mark - DFOriginalDetectIntentRequest

typedef GPB_ENUM(DFOriginalDetectIntentRequest_FieldNumber) {
  DFOriginalDetectIntentRequest_FieldNumber_Source = 1,
  DFOriginalDetectIntentRequest_FieldNumber_Version = 2,
  DFOriginalDetectIntentRequest_FieldNumber_Payload = 3,
};

/**
 * Represents the contents of the original request that was passed to
 * the `[Streaming]DetectIntent` call.
 **/
@interface DFOriginalDetectIntentRequest : GPBMessage

/**
 * The source of this request, e.g., `google`, `facebook`, `slack`. It is set
 * by Dialogflow-owned servers.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *source;

/**
 * Optional. The version of the protocol used for this request.
 * This field is AoG-specific.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/**
 * Optional. This field is set to the value of `QueryParameters.payload` field
 * passed in the request.
 *
 * This field is used for the telephony gateway. It should have a
 * structure similar to this JSON message:
 * <pre>{
 *  "telephony": {
 *    "caller_id": "+18558363987"
 *  }
 * }</pre>
 * Note: The caller ID field (`caller_id`) will be in
 * [E.164 format](https://en.wikipedia.org/wiki/E.164) and is only supported
 * for Enterprise Edition and not for Standard Edition agents. When the
 * telephony gateway is used with a standard tier agent the `caller_id` field
 * above will have a value of `REDACTED_IN_STANDARD_TIER_AGENT`.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *payload;
/** Test to see if @c payload has been set. */
@property(nonatomic, readwrite) BOOL hasPayload;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
